Entrega Proyecto 1
ChefeIdon/proyecto-1 pull request #1
Opened 2020-05-15 03:20 UTC by ChefeIdon

### Entrega Proyecto 1

- Tema Elegido:  1
- Link a GitHub Pages: https://chefeidon.github.io/proyecto-1/

Las aclaraciones están en el readme.md

2020-05-19 18:39 UTC, MarianoTucat requested changes
# Proyecto 1 - Agra

1. HTML: Mal
2. CSS: Bien
3. Javascript: Mal
4. Manejo DOM: Regular
5. Visualmente Atractiva: Muy Bien
6. Local Storage: Ausente
7. PR a tiempo: Si
8. GitHub Pages: Si
9. Video: Bien
Comentarios: Falta uso de Local Storage para almacenar los últimos 5 usos, los dos estilos diferentes. El código HTML está repetido innecesariamente, y el código JS abusa de la repetición y utiliza el atributo Title, habiendo mejores opciones. Mucho de lo  que está ahi se puede simplificar con arreglos y uso de ids para no repetir código. Lo mismo con el HTML, en vez de repetir el index 3 veces, se puede lograr lo mismo con el manejo del DOM en un único documento.
Resultado: Re-entrega

2020-05-19 22:03 UTC, ChefeIdon commented
Hola mariano, recibido! De paso te queria cuando es la fecha limite de
re-entrega. Saludos.

El mar., 19 may. 2020 15:39, Mariano Tucat <notifications@github.com>
escribió:

> *@MarianoTucat* requested changes on this pull request.
> Proyecto 1 - Agra
>
>    1. HTML: Mal
>    2. CSS: Bien
>    3. Javascript: Mal
>    4. Manejo DOM: Regular
>    5. Visualmente Atractiva: Muy Bien
>    6. Local Storage: Ausente
>    7. PR a tiempo: Si
>    8. GitHub Pages: Si
>    9. Video: Bien
>    Comentarios: Falta uso de Local Storage para almacenar los últimos 5
>    usos, los dos estilos diferentes. El código HTML está repetido
>    innecesariamente, y el código JS abusa de la repetición y utiliza el
>    atributo Title, habiendo mejores opciones. Mucho de lo que está ahi se
>    puede simplificar con arreglos y uso de ids para no repetir código. Lo
>    mismo con el HTML, en vez de repetir el index 3 veces, se puede lograr lo
>    mismo con el manejo del DOM en un único documento.
>    Resultado: Re-entrega
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ChefeIdon/proyecto-1/pull/1#pullrequestreview-414722924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXPKLYSKR4SWABFPEAAJODRSLG6XANCNFSM4NBG6SJA>
> .
>

2020-05-26 01:04 UTC, ChefeIdon commented
### Re-entrega Proyecto 1

- Tema Elegido:  1
- Link a GitHub Pages: https://chefeidon.github.io/proyecto-1/

Las aclaraciones están en el readme.md

2020-05-26 01:05 UTC, merged

2020-05-26 01:06 UTC, ChefeIdon commented
### Re-entrega Proyecto 1

- Tema Elegido:  1
- Link a GitHub Pages: https://chefeidon.github.io/proyecto-1/

Las aclaraciones están en el readme.md

2020-06-01 23:10 UTC, MarianoTucat commented
Veo que graba en local storage, pero cuando cargo la página nuevamente, la historia no es recuperada. Puede ser? De ser así, te pido que lo arregles, no debería ser muy complicado.

2020-06-01 23:57 UTC, ChefeIdon commented
Hola Mariano, ya corregí el problema, e hice un commit con los cambios.
Necesitas que haga otro pull request?

El lun., 1 jun. 2020 a las 20:11, Mariano Tucat (<notifications@github.com>)
escribió:

> Veo que graba en local storage, pero cuando cargo la página nuevamente, la
> historia no es recuperada. Puede ser? De ser así, te pido que lo arregles,
> no debería ser muy complicado.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/ChefeIdon/proyecto-1/pull/1#issuecomment-637173298>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACXPKL6SL4JYUROXZ7XZXMLRUQYQ7ANCNFSM4NBG6SJA>
> .
>

2020-06-02 01:22 UTC, MarianoTucat commented
excelente, está bien así nomás

2020-06-03 03:07 UTC, MarianoTucat commented
# Reentrega Proyecto 1 - Agra

1. HTML: Bien
2. CSS: Bien
3. Javascript: Regular
4. Manejo DOM: Bien
5. Visualmente Atractiva: Bien
6. Local Storage: Mal
7. PR a tiempo: Si
8. GitHub Pages: Si
9. Video: Bien
Comentarios: Ok
Estrellas: 🌟
Resultado: Aprobado